name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: python3 test.py
      id: python3-test-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: python3 test.py
        setup-command: ''
        command: python3 test.py
        timeout: 2
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PYTHON3-TEST-PY_RESULTS: "${{steps.python3-test-py.outputs.result}}"
      with:
        runners: python3-test-py
